#data source properties
spring.datasource.url=jdbc:postgresql://localhost:5432/botiq
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
#spring.datasource.password=system
#for prod
spring.datasource.password=0000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
server.address=0.0.0.0
server.port=8080
# spring.jackson.deserialization.fail-on-unknown-properties=true

##spring.mail.host=smtp-relay.gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username= dfiveone2020@gmail.com
#spring.mail.password=voam odbk vqqb yxqw
spring.mail.username=raghavendra.kedlaya@dfivetechnologies.com
spring.mail.password=qttu cxpw lmpa pjiw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true



server.servlet.session.timeout=30m
